### ISSUE TITLE
RSpec/FileName has the wrong namespace

### ISSUE THREAD

**Issue by williamn** [rubocop-hq/rubocop-rspec#21]
I got this message when running `rubocop`

```
/path/to/blog/.rubocop.yml: RSpec/FileName has the wrong namespace - should be Style
```

What seems to be wrong in my config file?

``` yml
Documentation:
  Enabled: false
require: rubocop-rspec
AllCops:
  RunRailsCops: true
```
