### ISSUE TITLE
Still getting "RSpec/FilePath has the wrong namespace - should be Rails"

### ISSUE THREAD

**Issue by dominicsayers** [rubocop-hq/rubocop-rspec#405]
If I run `rubocop` from the command line with the option ` --only RSpec/FilePath` I get the following:

```bash
$ rubocop --only RSpec/FilePath
--only option: RSpec/FilePath has the wrong namespace - should be Rails
Inspecting 21 files
.....................

$ rubocop -v
0.48.1

$ cat Gemfile.lock | grep rubocop-rspec
    rubocop-rspec (1.15.0)
  rubocop-rspec
```
My `.rubocop.yml` is as follows:

```YAML
---
require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.2
  DisplayCopNames: true
  Exclude:
    - 'tmp/**/*'

Style/MixinGrouping:
  Exclude:
    - 'spec/**/*.rb'

Metrics/BlockLength:
  CountComments: false  # count full line comments?
  Exclude:
    - '**/*_spec.rb'

StringLiterals:
  EnforcedStyle: single_quotes
  Enabled: true

DotPosition:
  EnforcedStyle: leading
  Enabled: true

ClassAndModuleChildren:
  EnforcedStyle: nested
  Enabled: true

Documentation:
  Enabled: false

FileName:
  Enabled: true

LineLength:
  Max: 120
  Enabled: true

Style/ExtraSpacing:
  Enabled: true

Lint/LiteralInInterpolation:
  AutoCorrect: true

Style/ModuleFunction:
  EnforcedStyle: extend_self # Allows us to have private methods too

Style/PercentLiteralDelimiters:
  # Hound and CodeClimate are currently using an old version of Rubocop with
  # different defaults, so we set them explicitly here.
  PreferredDelimiters:
    default: ()
    '%i': '[]'
    '%I': '[]'
    '%r': '{}'
    '%w': '[]'
    '%W': '[]'
```
