### ISSUE TITLE
ContextWording should allow "as" as a leader.

### ISSUE THREAD

**Issue by jcoyne** [rubocop-hq/rubocop-rspec#591]
```ruby
context 'as a visitor' do
...
end
```

**Comment by geniou** [comment]
@jcoyne Did you know you can configure this in your own project - something like this (`.rubocop.yml` file):

```yaml
RSpec/ContextWording:
   Prefixes:
     - as
     - for
     - when
     - with

```
