### ISSUE TITLE
Rails/HttpStatus not working after requiring rubocop-rspec

### ISSUE THREAD

**Issue by a14m** [rubocop-hq/rubocop-rspec#611]
After adding `require: rubocop-rspec` to the `.rubocop.yml`, the `Rails/HttpStatus` doesn't check the code, only the specs 

first reported here: https://github.com/bbatsov/rubocop/issues/5738#issuecomment-388838142

`rubocop-rspec 1.25.1`

**Comment by anthony-robin** [comment]
I think there is a conflict of cops name between `rubocop` and `rubocop-rspec` as `Rails/HttpStatus` is defined in both gems with the same namespace.

I'm not sure how we can fix that 🤔

**Comment by flyerhzm** [comment]
could we rename `Rails/HttpStatus` to `RSpec/Rails/HttpStatus`?

**Comment by dmytro-savochkin** [comment]
Since this is still a problem and it's hard to find out how to fix this maybe it would be better to rename `RSpec/Rails/HttpStatus` to `RSpec/StatusHttp`? Yes, it might be ugly but at least this won't have any conflicts...

**Comment by ixti** [comment]
Any news/plans on fixing this?

**Comment by ixti** [comment]
Right now I have to switch orders of requires to check both cops worked...

**Comment by ixti** [comment]
I have fixed this issue locally with following hacks:

``` ruby
# file: rubocop/fixes/http_status.rb
# frozen_string_literal: true

require "rubocop/cop/rails/http_status"
require "rubocop/cop/rspec/rails/http_status"

RuboCop::Cop::Cop.registry.instance_eval do
  [
    RuboCop::Cop::Rails::HttpStatus,
    RuboCop::Cop::RSpec::Rails::HttpStatus
  ].each do |cop|
    @registry.delete cop.badge
    @departments[cop.department].delete cop
    @cops_by_cop_name[cop.cop_name].delete cop
  end
end

module RuboCop
  module Cop
    module RSpec
      module Rails
        def HttpStatus.badge
          Badge.new("RSpec", "Rails/HttpStatus")
        end
      end
    end
  end
end

[RuboCop::Cop::Rails::HttpStatus, RuboCop::Cop::RSpec::Rails::HttpStatus]
  .each { |cop| RuboCop::Cop::Cop.registry.enlist cop }
```

---

``` yaml
# file: rubocop/fixes/http_status.yml

RSpec/Rails/HttpStatus:
  Description: Enforces use of symbolic or numeric value to describe HTTP status.
  Enabled: true
  EnforcedStyle: symbolic
  SupportedStyles:
  - numeric
  - symbolic
  StyleGuide: http://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/Rails/HttpStatus
```

---

``` yaml
# file: .rubocop.yml

require:
  - ./rubocop/fixes/http_status.rb

inherit:
  - ./rubocop/fixes/http_status.yml
```
