### ISSUE TITLE
Cop idea: prefer no parentheses: expect(subject).to eq(true) not expect(subject).to(eq(true))

### ISSUE THREAD

**Issue by hubertjakubiak** [rubocop-hq/rubocop-rspec#754]
Idea for cop suggestion:

Prefer `expect(subject).to eq(true)` not `expect(subject).to(eq(true))`. The same when `not_to` so `expect(subject).not_to eq(true)` not `expect(subject).not_to(eq(true))`.

There's no single option where second approach is used in https://github.com/rubocop-hq/rspec-style-guide.

**Comment by pirj** [comment]
Great idea.

There's [this](https://github.com/rubocop-hq/ruby-style-guide/#method-invocation-parens) in the Ruby Style Guide:
> Always omit parentheses for
> Methods that are part of an internal DSL (e.g., Rake, Rails, RSpec):
> # good
> validates :name, presence: true

Maybe add a cop here, and eventually a generic part if it to RuboCop, so that `rubocop-rails` could benefit from it as well, by marking `validates` and other Rails-specific DSL methods as such to be avoided.

Can't think of legit exceptions to this rule, e.g. when parenthesis would make sense.

**Comment by dgollahon** [comment]
> Can't think of legit exceptions to this rule, e.g. when parenthesis would make sense.

We just have to be careful of `to` in other contexts, notably the second `to` with this change matcher
```ruby
expect { man.you_cant_handle_the_truth! }.to change { man.the_truth? }.from(true).to(false)
```

**Comment by hubertjakubiak** [comment]
I actually fixed that with below custom config:

```
Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoredMethods:
    # long list of other methods that are also better without parentheses
    - to
    - not_to
```
