### ISSUE TITLE
Allow RSpec/MultipleExpectations to be higher for feature specs

### ISSUE THREAD

**Issue by cerdiogenes** [rubocop-hq/rubocop-rspec#793]

**Comment by pirj** [comment]
You may put an additional `.rubocop.yml` file in `features` directory and configure cops behaviour specific to that folder:

```yaml
# features/.rubocop.yml
RSpec/MultipleExpectations:
   Max: 20
```
