### ISSUE TITLE
Requiring `rubocop-rspec` forces Rubocop to apply `~/.rubocop.yml`

### ISSUE THREAD

**Issue by firedev** [rubocop-hq/rubocop-rspec#898]
```yml
# project/.rubocop.yml

require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
```
```yml
# ~/.rubocop.yml

AllCops:
  TargetRubyVersion: 2.3
```

Rubocop is working fine using the local `project/.rubocop.yml` unless `rubocop-rspec` is required. Then the rules from `~/.rubocop.yml` are applied and `TargetRubyVersion` becomes `2.3` which is unsupported. Probably other cops are applied on top of the existing configuration as well.

This is not the case when `rubocop-rspec` is not required.
